apiVersion: 1

datasources:
  - name: Prometheus
  - type: prometheus
  - access: proxy
  - uid: prom
  - isDefault: true
  # When running docker with --net=host, need to use 127.0.0.1 instead
  # of localhost.
  - url: http://127.0.0.1:9090
  - version: 1
  - editable: false
