app:
  build_buddy_url: "http://localhost:8080"
database:
  data_source: "sqlite3:///tmp/buildbuddy.db"
storage:
  ttl_seconds: 86400  # One day in seconds.
  chunk_file_size_bytes: 3000000  # 3 MB
  disk:
    root_directory: /tmp/buildbuddy
cache:
  max_size_bytes: 1000000000  # 1 GB
  in_memory: true
