name: Update Deps

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "website/**"

jobs:
  update:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'deps skip')"

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: buildbuddy

      - name: Checkout internal
        uses: actions/checkout@v5
        with:
          repository: "buildbuddy-io/buildbuddy-internal"
          ref: "master"
          token: ${{ secrets.BUILDBUDDY_APP_TOKEN }}
          path: buildbuddy-internal

      - name: Copy files from OSS to internal
        run: |
          cp buildbuddy/deps.bzl buildbuddy-internal/deps.bzl
          cp buildbuddy/.bazelversion buildbuddy-internal/.bazelversion
          cp buildbuddy/shared.bazelrc buildbuddy-internal/shared.bazelrc
          cp buildbuddy/bazel_downloader.cfg buildbuddy-internal/bazel_downloader.cfg
          mkdir -p buildbuddy-internal/buildpatches/bazel_dep
          cp buildbuddy/buildpatches/bazel_dep/* buildbuddy-internal/buildpatches/bazel_dep/
          mkdir -p buildbuddy-internal/deps
          cp buildbuddy/deps/* buildbuddy-internal/deps/
          cp buildbuddy/MODULE.bazel.lock buildbuddy-internal/MODULE.bazel.lock

      - name: Update SHA and lockfile
        run: |
          cd "$GITHUB_WORKSPACE"/buildbuddy-internal
          sed -i "s/commit = \"[a-z0-9]*\",  # autoupdate buildbuddy-io\/buildbuddy/commit = \"$GITHUB_SHA\",  # autoupdate buildbuddy-io\/buildbuddy/g" MODULE.bazel
          bazel mod deps --lockfile_mode=update

      - name: Commit
        env:
          AUTHOR_EMAIL: ${{ github.event.head_commit.author.email }}
          AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
        run: |
          cd "$GITHUB_WORKSPACE"/buildbuddy-internal
          git config --local user.email "$AUTHOR_EMAIL"
          git config --local user.name "$AUTHOR_NAME"
          git add deps.bzl
          git add .bazelversion
          git add shared.bazelrc
          git add bazel_downloader.cfg
          git add buildpatches
          git add deps
          git add MODULE.bazel.lock
          cat <<EOF > message.txt
          ðŸ”„ $COMMIT_MESSAGE
          Update buildbuddy-io/buildbuddy commit SHA

          ðŸ”— $COMMIT_URL
          EOF
          git commit -F message.txt -a

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: buildbuddy-internal
          repository: buildbuddy-io/buildbuddy-internal
          github_token: ${{ secrets.BUILDBUDDY_GITHUB_USER_TOKEN }}
          branch: master
